name: deploy lambda layers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - name: Run script file
      run: |
         chmod +x ./move_node_modules.sh
         ./move_node_modules.sh
      shell: bash
    - name: Create a zip file of node modules
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'lambda_layers.zip'  
        path : ./nodejs 
    - name: upload lambda layers zip file
      run: |
       aws lambda  publish-layer-version --layer-name alarm-layer --zip-file fileb://lambda_layers.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-south-1'
